# Generated by Django 3.1.5 on 2021-01-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('matricula', models.CharField(max_length=14, verbose_name='Matrícula')),
                ('campus', models.CharField(choices=[('CA', 'CA')], max_length=2)),
                ('cod_curso', models.CharField(max_length=10, verbose_name='Código do Curso')),
                ('desc_curso', models.TextField(verbose_name='Descrição do Curso')),
                ('email_acad', models.EmailField(max_length=254, verbose_name='E-mail Acadêmico')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('status_curso', models.CharField(choices=[('M', 'Matriculado'), ('D', 'Desativado')], default='M', max_length=1)),
                ('turma', models.CharField(max_length=20, verbose_name='Turma')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('febre', models.BooleanField(verbose_name='Febre')),
                ('cansaco', models.BooleanField(verbose_name='Cansaço')),
                ('tosse_seca', models.BooleanField(verbose_name='Tosse seca')),
                ('dor_corporal', models.BooleanField(verbose_name='Dores no corpo')),
                ('congestao_nasal', models.BooleanField(verbose_name='Congestão nasal')),
                ('dor_de_cabeca', models.BooleanField(verbose_name='Dor de cabeça')),
                ('conjuntivite', models.BooleanField(verbose_name='Conjuntivite')),
                ('dor_de_gargante', models.BooleanField(verbose_name='Dor de garganta')),
                ('diarreia', models.BooleanField(verbose_name='Diarréia')),
                ('perdeu_palador_ou_olfato', models.BooleanField(verbose_name='Perda do olfato ou paladar')),
                ('erupcao_cutanea_ou_descoloracao', models.BooleanField(verbose_name='Erupção cutânea ou descoloração da pele')),
                ('data_e_hora', models.DateTimeField(auto_now_add=True)),
                ('autorizacao_presenca', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TelefonesDosAlunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.aluno')),
            ],
        ),
    ]
