# Generated by Django 3.1.5 on 2021-02-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(verbose_name='Febre')),
                ('fatigue', models.BooleanField(verbose_name='Cansaço')),
                ('dry_cough', models.BooleanField(verbose_name='Tosse seca')),
                ('body_ache', models.BooleanField(verbose_name='Dores no corpo')),
                ('nasal_congestion', models.BooleanField(verbose_name='Congestão nasal')),
                ('headache', models.BooleanField(verbose_name='Dor de cabeça')),
                ('shortness_of_breathe', models.BooleanField(verbose_name='Falta de ar')),
                ('conjunctivitis', models.BooleanField(verbose_name='Conjuntivite')),
                ('sore_throat', models.BooleanField(verbose_name='Dor de garganta')),
                ('diarrhea', models.BooleanField(verbose_name='Diarréia')),
                ('loss_of_taste_or_smell', models.BooleanField(verbose_name='Perda do olfato ou paladar')),
                ('rash_or_discoloration', models.BooleanField(verbose_name='Erupção cutânea ou descoloração da pele')),
                ('other_symptons', models.TextField(default='Nenhum', verbose_name='Outros sintomas')),
                ('registration', models.CharField(default='00000000000000', max_length=14, verbose_name='Matrícula')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('attendance_authorization', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('matriculation', models.CharField(max_length=14, unique=True, verbose_name='Matrícula')),
                ('campus', models.CharField(choices=[('CA', 'CA')], max_length=2)),
                ('code_course', models.CharField(max_length=10, verbose_name='Código do Curso')),
                ('desc_course', models.TextField(verbose_name='Descrição do Curso')),
                ('email_acad', models.EmailField(max_length=254, verbose_name='E-mail Acadêmico')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Gênero')),
                ('status_course', models.CharField(choices=[('Matriculado', 'Matriculado'), ('Desativado', 'Desativado')], max_length=11, verbose_name='Estado no curso')),
                ('class_school', models.CharField(max_length=20, verbose_name='Turma')),
                ('shift', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=10, verbose_name='Turno')),
                ('photo', models.ImageField(blank=True, upload_to='users/pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='PhonesStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.student')),
            ],
        ),
    ]
