# Generated by Django 3.1.5 on 2021-01-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('matricula', models.CharField(max_length=14, verbose_name='Matrícula')),
                ('campus', models.CharField(choices=[('CA', 'CA')], max_length=2)),
                ('cod_curso', models.CharField(max_length=10, verbose_name='Código do Curso')),
                ('desc_curso', models.TextField(verbose_name='Descrição do Curso')),
                ('email_acad', models.EmailField(max_length=254, verbose_name='E-mail Acadêmico')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('status_curso', models.CharField(choices=[('M', 'Matriculado'), ('D', 'Desativado')], default='M', max_length=1)),
                ('turma', models.CharField(max_length=20, verbose_name='Turma')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonesDosAlunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.aluno')),
            ],
        ),
    ]
