# Generated by Django 3.1.5 on 2021-01-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'M'), ('Vespertino', 'V'), ('Noturno', 'N')], max_length=10),
        ),
    ]
