# Generated by Django 3.1.5 on 2021-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matriculation',
            field=models.CharField(max_length=14, unique=True, verbose_name='Matrícula'),
        ),
    ]
