# Generated by Django 3.1.5 on 2021-03-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210315_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.student'),
        ),
    ]
