# Generated by Django 3.1.5 on 2021-02-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210201_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='dor_corporal',
            new_name='body_ache',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='conjuntivite',
            new_name='conjunctivitis',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='diarreia',
            new_name='diarrhea',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='tosse_seca',
            new_name='dry_cough',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='cansaco',
            new_name='fatigue',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='febre',
            new_name='fever',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='dor_de_cabeca',
            new_name='headache',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='perdeu_palador_ou_olfato',
            new_name='loss_of_taste_or_smell',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='congestao_nasal',
            new_name='nasal_congestion',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='erupcao_cutanea_ou_descoloracao',
            new_name='rash_or_discoloration',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='dor_de_gargante',
            new_name='sore_throat',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='other_symptons',
            field=models.TextField(default='Nenhum', verbose_name='Outros sintomas'),
        ),
    ]
