# Generated by Django 3.1.5 on 2021-01-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210116_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='name',
            new_name='nome',
        ),
    ]
