# Generated by Django 3.1.5 on 2021-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'F'), ('Masculino', 'M')], max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_curso',
            field=models.CharField(choices=[('M', 'Matriculado'), ('D', 'Desativado')], default='M', max_length=1),
        ),
    ]
