# Generated by Django 3.1.5 on 2021-02-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210201_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='autorizacao_presenca',
            field=models.BooleanField(default=True),
        ),
    ]
