# Generated by Django 3.1.5 on 2021-02-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210201_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='autorizacao_presenca',
            new_name='attendance_authorization',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='data_e_hora',
            new_name='datetime',
        ),
    ]
