# Generated by Django 3.1.5 on 2021-01-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210124_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelefonesDosAlunos',
            new_name='TelefonesAlunos',
        ),
    ]
