# Generated by Django 3.1.5 on 2021-03-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210323_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='Entry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='dtenter',
            new_name='dt_enter',
        ),
    ]
