# Generated by Django 3.1.5 on 2021-01-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210124_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('febre', models.BooleanField(verbose_name='Febre')),
                ('cansaco', models.BooleanField(verbose_name='Cansaço')),
                ('tosse_seca', models.BooleanField(verbose_name='Tosse seca')),
                ('dor_corporal', models.BooleanField(verbose_name='Dores no corpo')),
                ('congestao_nasal', models.BooleanField(verbose_name='Congestão nasal')),
                ('dor_de_cabeca', models.BooleanField(verbose_name='Dor de cabeça')),
                ('conjuntivite', models.BooleanField(verbose_name='Conjuntivite')),
                ('dor_de_gargante', models.BooleanField(verbose_name='Dor de garganta')),
                ('diarreia', models.BooleanField(verbose_name='Diarréia')),
                ('perdeu_palador_ou_olfato', models.BooleanField(verbose_name='Perda do olfato ou paladar')),
                ('erupcao_cutanea_ou_descoloracao', models.BooleanField(verbose_name='Erupção cutânea ou descoloração da pele')),
                ('data_e_hora', models.DateTimeField(auto_now_add=True)),
                ('autorizacao_presenca', models.BooleanField()),
            ],
        ),
    ]
