# Generated by Django 3.1.5 on 2021-02-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210201_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='registration',
            field=models.CharField(default='00000000000000', max_length=14, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status_course',
            field=models.CharField(choices=[('M', 'Matriculado'), ('D', 'Desativado')], max_length=1, verbose_name='Estado no curso'),
        ),
    ]
