# Generated by Django 3.1.5 on 2021-03-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210324_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dt_enter',
            field=models.DateTimeField(),
        ),
    ]
