# Generated by Django 3.1.5 on 2021-02-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210209_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='student',
        ),
    ]
