# Generated by Django 3.1.5 on 2021-02-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_anamnese_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='shortness_of_breathe',
            field=models.BooleanField(default=False, verbose_name='Falta de ar'),
            preserve_default=False,
        ),
    ]
