# Generated by Django 3.1.5 on 2021-02-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210210_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status_course',
            field=models.CharField(choices=[('Matriculado', 'Matriculado'), ('Desativado', 'Desativado')], max_length=11),
        ),
    ]
