# Generated by Django 3.1.5 on 2021-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(verbose_name='Febre')),
                ('fatigue', models.BooleanField(verbose_name='Cançaso')),
                ('dry_cough', models.BooleanField(verbose_name='Tosse seca')),
                ('body_pain', models.BooleanField(verbose_name='Dores no corpo')),
                ('nasal_congestion', models.BooleanField(verbose_name='Congestão nasal')),
                ('headache', models.BooleanField(verbose_name='Dor de cabeça')),
                ('conjuntivite', models.BooleanField(verbose_name='Conjuntivite')),
                ('sore_throat', models.BooleanField(verbose_name='Dor de garganta')),
                ('diarreia', models.BooleanField()),
                ('loss_of_smell_or_taste', models.BooleanField(verbose_name='Perda de olfato ou paladar')),
                ('rash_or_discoloration', models.BooleanField(verbose_name='Erupção cutânea ou descoloração')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da resposta')),
                ('autorizacao', models.BooleanField(verbose_name='Autoriazação de presença')),
            ],
        ),
    ]
